version: '3.6'
services:
  postgres:
    image: postgres:12
    restart: always
    volumes:
    - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgrespassword
    networks:
      local:
  web:
    build: .
    restart: always
    networks:
      local:
    ports:
      - "4200:4200"
    volumes:
      - ./workspace:/usr/app
    depends_on:
      - graphql-engine
  graphql-engine:
    image: hasura/graphql-engine:v2.0.0-alpha.7.cli-migrations-v3
    ports:
      - 8080:8080
    depends_on:
      - postgres
    restart: always
    volumes:
      - ./db/migrations:/hasura-migrations
      - ./db/metadata:/hasura-metadata
    networks:
      local:
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:postgrespassword@postgres:5432/postgres
      ## enable the console served by server
      HASURA_GRAPHQL_ENABLE_CONSOLE: "false" # set to "false" to disable console
      ## enable debugging mode. It is recommended to disable this in production
      HASURA_GRAPHQL_DEV_MODE: "true"
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      ## uncomment next line to set an admin secret
      # HASURA_GRAPHQL_ADMIN_SECRET: myadminsecretkey
networks:
  local: 
volumes:
  db_data:

